#!/usr/bin/env python3
"""Injects API keys into the generated Xcode scheme's Run environment
variables, so a plain Xcode ▶️ Run carries them automatically — no manual
retyping into the app's in-app fields, no devicectl -e relaunch needed
every time.

Reads secrets from macOS Keychain only, never prints them. Writes into
EmotionPOC.xcodeproj/.../*.xcscheme, which is gitignored (regenerated by
`xcodegen generate`, never committed) — so this never puts a secret into
any tracked file. Re-run this after every `xcodegen generate`, since that
overwrites the scheme files.
"""
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
KEYCHAIN_ACCOUNT = subprocess.run(["whoami"], capture_output=True, text=True).stdout.strip()

# (env var name written into the scheme, Keychain service name)
KEYS = [
    ("OPENROUTER_API_KEY", "EmotionPOC_OPENROUTER_API_KEY"),
    ("REQUESTY_API_KEY", "EmotionPOC_REQUESTY_API_KEY"),
    ("GEMINI_API_KEY", "EmotionPOC_GEMINI_API_KEY"),
]


def keychain_read(service):
    result = subprocess.run(
        ["security", "find-generic-password", "-a", KEYCHAIN_ACCOUNT, "-s", service, "-w"],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        return None
    return result.stdout.strip()


def inject(scheme_path: Path, env_pairs: list[tuple[str, str]]):
    text = scheme_path.read_text()

    entries = "\n".join(
        f'         <EnvironmentVariable\n'
        f'            key = "{key}"\n'
        f'            value = "{value}"\n'
        f'            isEnabled = "YES">\n'
        f'         </EnvironmentVariable>'
        for key, value in env_pairs
    )
    block = f"      <EnvironmentVariables>\n{entries}\n      </EnvironmentVariables>\n   </LaunchAction>"

    if "<EnvironmentVariables>" in text:
        text = re.sub(
            r"      <EnvironmentVariables>.*?</EnvironmentVariables>\n   </LaunchAction>",
            block, text, flags=re.DOTALL,
        )
    else:
        text = text.replace("   </LaunchAction>", block, 1)

    scheme_path.write_text(text)


def main():
    env_pairs = []
    for env_name, service in KEYS:
        value = keychain_read(service)
        if value:
            env_pairs.append((env_name, value))
        else:
            print(f"  (skip) {env_name}: not found in Keychain (service {service})", file=sys.stderr)

    if not env_pairs:
        print("No keys found in Keychain — nothing injected.", file=sys.stderr)
        return

    scheme_dir = REPO_ROOT / "EmotionPOC.xcodeproj" / "xcshareddata" / "xcschemes"
    schemes = list(scheme_dir.glob("*.xcscheme")) if scheme_dir.is_dir() else []
    if not schemes:
        print(f"No .xcscheme files found under {scheme_dir} — run `xcodegen generate` first.", file=sys.stderr)
        return

    for scheme_path in schemes:
        inject(scheme_path, env_pairs)
        print(f"Injected {len(env_pairs)} env var(s) into {scheme_path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
