-- Guided journal flow change: single open-ended anchor question + up to 2
-- chained follow-ups (hard cap: 3 questions total per entry), superseding
-- the "3 main questions from a bank" model from 20260825000001. Decided
-- 2026-08-30 after walking through the updated flow diagram: "1 anchor,
-- rantai followup, total 3 pertanyaan" — each follow-up in the chain is
-- evaluated against the PREVIOUS answer (evaluate-parent-log-followup),
-- not picked from a randomized pool anymore.
--
-- parent_log_answers' old unique(parent_log_entry_id, field, source)
-- assumed at most one followup per field. The new chain can produce two
-- followup rows sharing the SAME field (the anchor's field, always
-- FEELING now, since there's no more per-field main-question bank) —
-- replaced with a sequence-based constraint (0 = anchor, 1/2 = chained
-- followups) instead.

alter table parent_log_answers add column if not exists sequence smallint not null default 0;

-- Backfill: every existing row defaulted to sequence 0 on insert (the
-- column didn't exist before this migration), so entries with more than
-- one row (old 3-main-question test entries, some with followups) collide
-- on the new unique constraint below. Assign each entry's own rows an
-- incrementing sequence ordered by creation time — these are POC/staging
-- test entries created under the pre-chain model, they don't need to carry
-- the new anchor(0)/followup(1,2) semantics exactly, they just need to
-- satisfy uniqueness.
update parent_log_answers pla
set sequence = sub.rn
from (
  select id, row_number() over (partition by parent_log_entry_id order by created_at) - 1 as rn
  from parent_log_answers
) sub
where pla.id = sub.id and pla.sequence <> sub.rn;

do $$
declare
  old_constraint text;
begin
  select conname into old_constraint
  from pg_constraint
  where conrelid = 'parent_log_answers'::regclass
    and contype = 'u'
    and conkey = (
      select array_agg(attnum order by attnum)
      from pg_attribute
      where attrelid = 'parent_log_answers'::regclass
        and attname in ('parent_log_entry_id', 'field', 'source')
    );
  if old_constraint is not null then
    execute format('alter table parent_log_answers drop constraint %I', old_constraint);
  end if;
end $$;

alter table parent_log_answers
  drop constraint if exists parent_log_answers_entry_sequence_key;
alter table parent_log_answers
  add constraint parent_log_answers_entry_sequence_key unique (parent_log_entry_id, sequence);

comment on table parent_log_answers is
  'source = main: the single open-ended anchor question (sequence 0). '
  'source = followup: up to 2 chained followups (sequence 1, 2), each '
  'generated by evaluate-parent-log-followup against the PRIOR answer in '
  'the chain. Hard cap of 3 rows total per entry, enforced client-side '
  '(the client stops calling evaluate-parent-log-followup once it holds '
  '3 answers, regardless of has_cognitive_mechanism).';
